name: flutwid_ui
description: A Flutter component generator tool.
version: 2.1.2
repository: https://github.com/kirubeldess/flutwid_ui

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.7.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0

executables:
  flutwid_ui: flutwid_ui

flutter:
  uses-material-design: true
