name: flutwid_ui
description: A Flutter UI component library.
version: 1.3.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  args: ^2.7.0
  mustache_template: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0
  
executables:
  flutwid_ui: flutwid_ui

flutter:
  uses-material-design: true

repository: https://github.com/kirubeldess/flutwid_ui
